version: "3"

services:
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - storm

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - kafka
    networks:
      - storm
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092

  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - zookeeper
      - kafka
    networks:
      - storm
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
    ports:
      - '8080:8080' # Storm UI

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - storm

  storm-supervisor:
    image: 'storm:2.4.0'
    command: storm supervisor
    depends_on:
      - zookeeper
      - consumer
    networks:
      - storm
    volumes:
      - './storm-supervisor/storm.yaml:/conf/storm.yaml'

networks:
  storm:
