version: "3"

services:
  kafka:
    container_name: aic-kafka
    build: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - storm

  producer:
    container_name: aic-producer
    build:
      context: .
      dockerfile: producer/Dockerfile
      args:
        - TAXI_DATA_FOLDER=${TAXI_DATA_FOLDER}
    depends_on:
      - kafka
    networks:
      - storm
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      TAXI_DATA_FOLDER: ${TAXI_DATA_FOLDER}
      TAXI_DATA_SPEED: ${TAXI_DATA_SPEED}
      NUMBER_TAXIS: ${NUMBER_TAXIS}


  consumer:
    container_name: aic-consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - zookeeper
      - kafka
      - redis
    networks:
      - storm
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      REDIS_HOST: redis:6379
    ports:
      - '8080:8080' # Storm UI

  zookeeper:
    container_name: aic-zookeeper
    image: 'bitnami/zookeeper:latest'
    platform: linux/amd64
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - storm

  storm-supervisor:
    container_name: aic-supervisor
    build: storm-supervisor
    platform: linux/amd64
    depends_on:
      - zookeeper
      - consumer
    networks:
      - storm
    environment:
      WAIT_NIMBUS: consumer:6627

  redis:
    container_name: aic-redis
    build: redis
#    ports:
#      - '6379:6379' # Local inspection
    networks:
      - storm

#  redis-example:
#    build:
#      context: .
#      dockerfile: ./redis-example/Dockerfile
#    depends_on:
#      - redis
#    networks:
#      - storm
#    environment:
#      REDIS_HOST: redis:6379

  frontend:
    container_name: aic-frontend
    build: frontend
    networks:
      - web-frontend

networks:
  storm:
  web-frontend:
